### ISSUE TITLE
Imperfect execution system

### ISSUE THREAD

**Issue by Trevodorax** [c-lings/clings#2]
Lacking some cases, and not getting the right output for each kind of failure

**Comment by TheRealHoko** [comment]
Do you have examples ?

**Comment by Trevodorax** [comment]
Yup:
- the output of the compiler error is not retrieved by the program
- the output of the program is not retrieved by the program
- if I remember well, the execution doesn't care about the exit status (EXIT_FAILURE or EXIT_SUCCESS)
- again if my memories are good, when the program crashes (segfault), the exercise is considered as a success (woopsies)

**Comment by TheRealHoko** [comment]
> the output of the compiler error is not retrieved by the program
> the output of the program is not retrieved by the program
> if I remember well, the execution doesn't care about the exit status (EXIT_FAILURE or EXIT_SUCCESS)
Done

> again if my memories are good, when the program crashes (segfault), the exercise is considered as a success (woopsies)
which kata does a segfault ? I'm seeing a run error but it doesn't segfault on my machine (which should imo)

**Comment by TheRealHoko** [comment]
Also where should the output be saved ? file ? result buffer ?

**Comment by Trevodorax** [comment]
Great for the Done ones !

The run_error is basically a guaranteed segfault, that's odd...

For the output, it should be stored in the result, which is a buffer yup

**Comment by ohmushi** [comment]
Close with https://github.com/c-lings/clings/pull/19
