### ISSUE TITLE
Is testing doubting?

### ISSUE THREAD

**Issue by ohmushi** [c-lings/clings#6]
Where the duck are tests ?

**Comment by ohmushi** [comment]
I think we should add Github Actions to run the tests on PR 
AND 
maybe a local git hooks on dev pcs to run the tests before push

**Comment by TheRealHoko** [comment]
In terms of productivity is it better to have hooks locally ?

**Comment by ohmushi** [comment]
Yes, this gives you much faster feedback than if you had to wait for a pull request to trigger the tests action.
Generally speaking, we always try to get feedback as quickly as possible.
In the case of a hook, this would save time and avoid polluting the remote by not even push if the tests don't pass.

**Comment by ohmushi** [comment]
Okay, I've done my homework 🤓 

For the testing libs I started with this [stackoverflow](https://stackoverflow.com/questions/65820/unit-testing-c-code).
And I assume that we want the lib present on the package managers (Vcpck, Conan, maybe ...Nix ?) 

So the candidates are:

- [Cmocka](https://cmocka.org/)
- [CUnit](https://cunit.sourceforge.net/)

Special mention for lib in a single .h:
- [MinUnit](https://github.com/siu/minunit/blob/master/minunit.h) (version boosted)

If we are ok with embedding the lib sources:

- [Criterion](https://github.com/Snaipe/Criterion)
- [AceUnit](https://aceunit.sourceforge.net/)
- [CUnit for Mr.Ando.](http://park.ruru.ne.jp/ando/work/CUnitForAndo/html/)
- [CuTest](https://cutest.sourceforge.net/)
- [Embedded Unit](https://sourceforge.net/projects/embunit/)
- [HWUT](https://sourceforge.net/projects/hwut/)
- [CGreen](https://github.com/cgreen-devs/cgreen)
- [CppUnit](https://cppunit.sourceforge.net/doc/cvs/index.html)

**Comment by ohmushi** [comment]
And I have a suggestion... shouldn't we run the tests with Valgrind ?

**Comment by ohmushi** [comment]
Well, I started yesterday with Cmocka, it looked very nice (mocking in C, I was dreaming about it) but I've been trying all day to mock my functions and it's a sad failure. I couldn't figure out how to mock on my pc (macosX), and the more code and forums I read, the more I realized that cmocka isn't very portable. So I gave up on cmocka.

Today is another day, I've switched to CUnit, which is much more basic but robust and portable.
And it works and it's pretty easy to use.
I've integrated CTest, so you can run the ctest command and get coverage with ctest -T Coverage. I was also able to obtain coverage by running CTest integrated into my IDE.

The next step is to get a better coverage report. I tried to integrate Gcov but without success. I think it would be much better and could be integrated into a CI/CD.

**Comment by Trevodorax** [comment]
Thanks so much for the test investigation !

Definitely agree on valgrind, and on the CI integration, it would be sooo cool to have everything tested for memory leaks AND from other errors systematically :DD
